In [3]:
from PIL import Image
import numpy as np
import sys
import os
import csv

In [4]:
def resize_images(directory, output_size):

    output_directory = os.path.join(directory, 'resized')
    os.makedirs(output_directory, exist_ok=True)
    
    for filename in os.listdir(directory):
        try:
            with Image.open(os.path.join(directory, filename)) as img:
                resized_img = img.resize(output_size)
                
                resized_img.save(os.path.join(output_directory, filename))
                print(f"{filename} resized successfully.")
        except Exception as e:
            print(f"Error resizing {filename}: {e}")

directory = r'C:\Users\tharu\623P\Chatter_free'
output_size = (640, 480)  

# Resize images
resize_images(directory, output_size)


Error resizing resized: [Errno 13] Permission denied: 'C:\\Users\\tharu\\623P\\Chatter_free\\resized'
T1_1000doc_192RPM_02_02_24 (3)_T8.bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (3)_T13.bmp resized successfully.
T1_1000doc_192RPM_05_02_24.bmp resized successfully.
T1_200doc_192RPM_02_02_24 (2).bmp resized successfully.
T1_200doc_192RPM_02_02_24 (3).bmp resized successfully.
T1_200doc_192RPM_02_02_24 (4).bmp resized successfully.
T1_200doc_192RPM_02_02_24 (4)_T9.bmp resized successfully.
T1_200doc_192RPM_02_02_24 (5).bmp resized successfully.
T1_200doc_192RPM_02_02_24.bmp resized successfully.
T1_200doc_192RPM_02_02_24_T10.bmp resized successfully.
T1_200doc_192RPM_05_02_24 (2).bmp resized successfully.
T1_200doc_192RPM_05_02_24 (2)_T14.bmp resized successfully.
T1_200doc_192RPM_05_02_24 (3).bmp resized successfully.
T1_200doc_192RPM_05_02_24 (4).bmp resized successfully.
T1_200doc_192RPM_05_02_24 (5).bmp resized successfully.
T1_200doc_192RPM_05_02_24.bmp resized successfull

In [5]:
def resize_images(directory, output_size):
    output_directory = os.path.join(directory, 'resized')
    os.makedirs(output_directory, exist_ok=True)

    for filename in os.listdir(directory):
        try:
            with Image.open(os.path.join(directory, filename)) as img:
                resized_img = img.resize(output_size)
            
                resized_img.save(os.path.join(output_directory, filename))
                print(f"{filename} resized successfully.")
        except Exception as e:
            print(f"Error resizing {filename}: {e}")

directory = r'C:\Users\tharu\623P\Chatter'

output_size = (640, 480) 

# Resize images
resize_images(directory, output_size)


Error resizing resized: [Errno 13] Permission denied: 'C:\\Users\\tharu\\623P\\Chatter\\resized'
T1_1000doc_192RPM_02_02_24 (2)_T9.bmp resized successfully.
T1_1000doc_192RPM_02_02_24 (3)_T10.bmp resized successfully.
T1_1000doc_192RPM_02_02_24 (4)_T11.bmp resized successfully.
T1_1000doc_192RPM_02_02_24 (5)_E.bmp resized successfully.
T1_1000doc_192RPM_02_02_24 (5)_T12.bmp resized successfully.
T1_1000doc_192RPM_02_02_24.bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (10).bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (2).bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (2)_T15.bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (3).bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (4).bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (5).bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (6).bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (7).bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (8).bmp resized successfully.
T1_1000doc_192RPM_05_02_24 (9)

In [6]:
def createFileList(myDir, format='.bmp'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList(r'C:\Users\tharu\623P\traindata')

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("in_put.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)


C:\Users\tharu\623P\traindata
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_02_02_24 (2)_T9.bmp
[195 159 106 ... 125 120 116]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_02_02_24 (3)_T10.bmp
[169 169 172 ...  29  33  38]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_02_02_24 (4)_T11.bmp
[118 147 169 ... 121 118 116]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_02_02_24 (5)_E.bmp
[190 185 168 ...   1   2   2]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_02_02_24 (5)_T12.bmp
[142 142 132 ...  52  50  46]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_02_02_24.bmp
[61 73 49 ...  1  3 11]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_05_02_24 (2).bmp
[ 1  1  1 ... 49 42 37]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_05_02_24 (2)_T15.bmp
[ 1  1  1 ... 29 20 10]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_05_02_24 (3).bmp
[  2   2   2 ... 115 117 109]
C:\Users\tharu\623P\traindata\T1_1000doc_192RPM_05_02_24 (4).bmp
[215 196 204 ...  34  37  35]
C:\Users\tharu\623P\t

In [7]:
def createFileList(myDir, format='.bmp'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList(r'C:\Users\tharu\623P\testingdata')

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("in_put_test.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)

C:\Users\tharu\623P\testingdata
C:\Users\tharu\623P\testingdata\T1_1000doc_192RPM_02_02_24 (3)_T8.bmp
[195 195 194 ...  18  17  17]
C:\Users\tharu\623P\testingdata\T1_1000doc_192RPM_05_02_24 (10).bmp
[115 127 149 ...  91  88  85]
C:\Users\tharu\623P\testingdata\T1_1000doc_192RPM_05_02_24 (3)_T13.bmp
[ 30  43  60 ... 108 126 144]
C:\Users\tharu\623P\testingdata\T1_1000doc_192RPM_05_02_24 (8).bmp
[155 151 157 ...  84  84  84]
C:\Users\tharu\623P\testingdata\T1_1000doc_192RPM_05_02_24 (9).bmp
[163 153 139 ...  47  37  52]
C:\Users\tharu\623P\testingdata\T1_1000doc_192RPM_05_02_24.bmp
[209 229 238 ...  52  54  51]
C:\Users\tharu\623P\testingdata\T1_1000doc_192RPM_05_02_24_T16.bmp
[119  92  83 ...  21  22  24]
C:\Users\tharu\623P\testingdata\T1_1000doc_250RPM_02_02_24 (2).bmp
[2 2 2 ... 2 1 1]
C:\Users\tharu\623P\testingdata\T1_1000doc_550RPM_22_1_24 (2).bmp
[239 239 239 ...   1   1   1]
C:\Users\tharu\623P\testingdata\T1_1000doc_715RPM_22_1_24 (2).bmp
[239 239 239 ...   7   7   9]
C:\Users